name: PR Notification

on:
  pull_request:
    types: [opened, reopened, closed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: MS Teams PR Notification
        uses: N-Evan/teams-notification-action-custom@v1.0.2
        with:
          webhook_url: ${{ secrets.TEAMS_WEBHOOK_URL }}
          pr_title: ${{ github.event.pull_request.title }}
          pr_url: ${{ github.event.pull_request.html_url }}
          pr_creator: ${{ github.event.pull_request.user.login }}
          repo_name: ${{ github.repository }}
